### PR TITLE
show translated errors instead of the label

### PR DESCRIPTION
**Pull request by WalterLuis**
## Description

I do not know if it will be the best way to put the code, I added in most of the `\App\Exceptions\AppException` the `\App\Language::translate` so that the translation of the error appears instead of its label.

#### BEFORE
chrome_2017-11-23_11-38-39

#### AFTER
chrome_2017-11-23_11-39-15

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code is written according to the guidelines found [here] (https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/how-to-create-php-files).
- [X] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Comment by mariuszkrzaczkowski** [comment]
We have removed the translation from those places where you added because this mechanism has been rebuilt.
Currently, the translations for exceptions should be in the file languages/_lang_/Other/Exceptions.php
I've added a correction for your case https://github.com/YetiForceCompany/YetiForceCRM/commit/29a271009aa9d8efd10419103e99844a13d176fc

**Comment by mariuszkrzaczkowski** [comment]
I know there are places where you need to improve it.

**Comment by WalterLuis** [comment]
Okey, thank you.
To translate them, should they be in /lang/Other/Exceptions.php? or I have to have something else in mind

**Comment by mariuszkrzaczkowski** [comment]
So should be in /lang/Other/Exceptions.php

**Pull request closed without merging**
