### PR TITLE
Improved quick preview view in related list in preview

### PR DESCRIPTION
**Pull request by konadrian**
Improved quick preview view in related list in preview
bylo
jest

### CODE REVIEW

**Comment by maninvatsa** [comment]
I was wondering if the Record preview list can be default option rather than selecting manually ? 

screenshot 2018-12-05 at 16 04 33

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/ab4daa921f3054a4edb0546a4f7a9dee54edda32/config/modules/Accounts.php#L20

**Comment by mariuszkrzaczkowski** [comment]
/config/modules/Contacts.php
'defaultViewName' => 'List',

**Comment by maninvatsa** [comment]
There's no Contacts.php

screenshot 2018-12-05 at 16 35 03

**Comment by mariuszkrzaczkowski** [comment]
Add new

**Pull request merged**
