### PR TITLE
user.ini - PHP directives with PHP_INI_SYSTEM mode

### PR DESCRIPTION
**Pull request by davide-alghi**
**PHP_INI_SYSTEM** (removed)
some PHP directives into .user.ini and public_html/.user.ini have PHP_INI_SYSTEM mode: these directives shoud not be into .user.ini

- file_uploads
- allow_url_fopen
- mbstring.func_overload
- expose_php
- allow_url_include
- disable_functions
- opcache.enable_cli
- opcache.max_accelerated_files
- opcache.interned_strings_buffer
- opcache.save_comments
- realpath_cache_size
- realpath_cache_ttl
- mysqlnd.collect_memory_statistics

**Duplicated directives** (removed)
- session.cookie_httponly

**Out of YF requirements** (set to required values)
- zlib.output_compression (On in .user.ini, Off in YF requirements)

___
### notes

**opcache.enable**: some systems could crash if Opcache is double-enabled: php.ini and .user.ini, often with fastCGI (php-fpm)

**Magento 2**: ```opcache.save_comments = 0``` (PHP_INI_SYSTEM mode) could have problems with Magento 2 if installed on same server. Problems with products or some sections show blank page (is random, depend on objects order creation and cache).
https://devdocs.magento.com/guides/v2.3/install-gde/trouble/php/tshoot_opcache.html
https://magento.stackexchange.com/questions/271048/magento-2-2-3-1-each-method-must-have-a-doc-block-see-magento-eav-api-attri
https://magento.stackexchange.com/questions/124395/getting-error-in-magento-2-1-add-to-product-in-admin

### CODE REVIEW

**Comment by mariuszkrzaczkowski** [comment]
Thanks @davide-alghi  good work

**Comment by davide-alghi** [comment]
### Note +

**Magento 2**
```opcache.enable_cli = On``` for **CLI** (not for Apache or fpm) arises an issue on _Magento 2 installation via composer_.

```
Installing database schema:

In ResourceConnection.php line 149:
Connection "default" is not defined
```
opcache enable_cli

_workaround_
1. set for CLI ```opcache.enable_cli = Off```
2. install Magento 2 (via composer)
3. set for CLI ```opcache.enable_cli = On```

PS: IMHO opcache.enable_cli could remain Off

**Comment by mariuszkrzaczkowski** [comment]
Can you please explain me what does it have to do with CRM? 
This is a bug in Magent and it's their problem.

**Comment by davide-alghi** [comment]
You are integrating YF with Magento and this problem may arise in the future if some user installs YF and Magento on the same server. Only shared knowledge.

**Comment by mariuszkrzaczkowski** [comment]
Thanks for the info, these are two different systems and they require two different configurations, so they have to be separated properly.

**Pull request closed without merging**
