### PR TITLE
Taxation resetted to default if tax mode is group [important]

### PR DESCRIPTION
**Pull request by davide-alghi**
## Description
Conditions: a taxations is defined as default and inventory entity has tax mode = group
If the inventory entity is re-edited, taxes are resetted to default tax

before
before

after
after

## Testing
on GitHub Developer

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code is written according to the guidelines found [here] (https://github.com/php-fig/fig-standards).
- [ ] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Review by rskrzypczak — APPROVED** [review]

**Comment by vovpff** [comment]
@rskrzypczak @davide-alghi after this commit global tax not resetted in tax block but when record edited every new added line item has 0% tax as default (not global). I will open an issue tomorrow.

**Comment by davide-alghi** [comment]
> @rskrzypczak @davide-alghi after this commit global tax not resetted in tax block but when record edited every new added line item has 0% tax as default (not global). I will open an issue tomorrow.

@vovpff, good morning Vladimir,
yes, you are right. I'll do a new pull request as soon as possible, so you will can test it.

**Comment by vovpff** [comment]
@davide-alghi nice to hear you!
#13034

**Comment by davide-alghi** [comment]
@vovpff thx, for me too ;)
if you wanna try if the problem is fixed

https://github.com/YetiForceCompany/YetiForceCRM/pull/13035/files

**Pull request merged**
