### PR TITLE
Fix installation process

### PR DESCRIPTION
**Pull request by WalterLuis**
## Changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code is written according to the guidelines found [here] (https://yetiforce.com/en/developer-documentation/standards/167-how-to-create-php-files.html).
- [x] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Comment by mariuszkrzaczkowski** [comment]
I have reversed one change of
https://github.com/YetiForceCompany/YetiForceCRM/commit/e05bca49109e47d9acf63900b84d9379533c0eb9

output_buffering On ! = 1

Output_buffering can have a value of 1 but this is not the same as "On"

**Comment by WalterLuis** [comment]
In my php i have this configuration:
php_output_buffering

from phpinfo();
inf1_output_buffering
inf_output_buffering

from crm:
crm_output_buffering

I may be wrong, but in my version of php it looks like it's the same '1' and 'On'

**Comment by mariuszkrzaczkowski** [comment]
Do it this way :
output_buffering = "On"

**Comment by WalterLuis** [comment]
Now it's okay, I had not thought to put quotation marks:
inf2_output_buffering

thanks :D

**Pull request merged**
