### PR TITLE
[IMPROVEMENT] BE: Colors and calendar / Calendar - Holidays - YFBL0095

### PR DESCRIPTION
**Pull request by davide-alghi**
[IMPROVEMENT] BE: Colors and calendar / Calendar - Holidays

fixed bugs / reworked behaviors
1) every time I make a change, time range resets
2) not able to set time range by hand
3) if edit modal win is open/closed, open/closed, open/closed and then changed/saved, many messages are shown
4) if date is saved without change, the message "Failed to modify public holiday" is confusing
5) if no date range is set, only current year records are shown
6) delete without confirmation

new features / files
1) restyled responsivity
2) added mass delete and mass duplicate
3) date range reset button available
4) added css file
5) added record model
6) reworked module model
7) records loaded via Ajax

fixed and tested on YF 5.3.315

Before
before

After
after

### CODE REVIEW

**Comment by rskrzypczak** [comment]
Thank you for your contribution.
just a couple of things to keep in mind in the future:
- try to always use 3 eqal signs instead of just 2 (===)
- try to format the code at least a little properly :) (https://github.com/YetiForceCompany/YetiForceCRM/pull/13734/files#diff-1757d97cb5775a4d4c9892fde3d2d8c17789263e900bacf3df32abfd13a9a205)

**Comment by davide-alghi** [comment]
Good morning Radosław,

> * try to always use 3 eqal signs instead of just 2 (===)

pls show me where value and type had to be compared (===)

____________

> * try to format the code at least a little properly

I think that is a GitHub diff preview issue. I hate bad indentation so I pay a lot of attention for that :)

In my Visual Studio Code indentation is good and also in my branch
https://github.com/davide-alghi/YetiForceCRM/blob/e3bd994f3a86afc93d30e36a99aeb0c3a019b2c2/modules/Settings/PublicHoliday/models/Record.php#L1

and also in YF master indentation is good
https://github.com/YetiForceCompany/YetiForceCRM/blob/f2d2f3cccec12a51a2655ac46b8937ad36de01a3/modules/Settings/PublicHoliday/models/Record.php#L1

**Comment by davide-alghi** [comment]
> * try to format the code at least a little properly

yes something is wrong, but I cannot understand why ... the raw version is bad indented :(
have you an idea?

https://raw.githubusercontent.com/YetiForceCompany/YetiForceCRM/f2d2f3cccec12a51a2655ac46b8937ad36de01a3/modules/Settings/PublicHoliday/models/Record.php

**Comment by davide-alghi** [comment]
OK I do both the question and the answer :D
I talk to myself :D

I just downloaded the zip code (YetiForceCRM-developer.zip) and indentation is good ... I'm saved :)

A thing I remember. For this branch I did an unusual thing: I created and deleted the branch with the same name twice and then recreated it for the third and final time, again with the same name. Maybe this creates problems for GitHub (?). That's the only thing I can think of.

**Comment by davide-alghi** [comment]
> * try to format the code at least a little properly

found the problem: some lines were indented with space chars not with tab char, in Record.php

**Comment by rskrzypczak** [comment]
Generally quite a few things in this pull request should be improved.
In this commit https://github.com/YetiForceCompany/YetiForceCRM/commit/2198c54ca17bc45d7ae1d085bfa43029a96a8986 there were some minor fixes. 
Look through the changes there and try to write your code in a similar way. 

Pay attention to the following:
- DocBlock
- avoiding all php type messages (eg. notice)
- separating views and actions   // never overwrite the getViewer() function
- minimizing and optimizing the code
- avoiding initiating events in tpl-s directly, eg. onsubmit, onclick, etc.
- basing the layout on bootstrap4

P.S.
The next pull requests won't be so easily accepted ;)

**Pull request merged**
