### PR TITLE
Translate in Romanian ro_ro

### PR DESCRIPTION
**Pull request by cltvchannel**
## Description

Add Romanian language.
## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code is written according to the guidelines found [here] (https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/how-to-create-php-files).
- [ ] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Comment by paula-w** [comment]
Hi @cltvchannel 
let us know when you finish adding the translations so we can accept them.
Thanks a lot for helping us make YetiForce even better!

**Comment by cltvchannel** [comment]
I am trying to finish this translation in two days.
Thanks !

**Comment by paula-w** [comment]
When do you think you can finish the translation? We're soon going to release the new version, and we'd love to be able to include all your great work in it

**Comment by cltvchannel** [comment]
Tomorrow the translation will be ready.

**Comment by cltvchannel** [comment]
@paula-w is necesary to add sql query for translation?
If not, you can merge this commit.

**Comment by paula-w** [comment]
Only translate the language files, we will take care of everything else. Thanks!

**Comment by paula-w** [comment]
Hi @cltvchannel , just to make sure - is everything finished and ready for us to merge?  Thanks!

**Comment by cltvchannel** [comment]
Hi @paula-w , you can merge this.

**Comment by cltvchannel** [comment]
Yes, i am planning to translate them.
Thanks !

**Comment by paula-w** [comment]
Hi @cltvchannel , we just merged your pull request. If you want to add the remaining translations please open a new pull request. Thanks!

**Pull request merged**
