### PR TITLE
add logged in userid

### PR DESCRIPTION
**Pull request by migoi**
## Description

Add userId from logged in user to response from webservice api. This make it possible to know the current user id on creating new records.

## Testing

See demo in YetiForceScripts.

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code is written according to the guidelines found [here] (https://yetiforce.com/en/developer-documentation/standards/167-how-to-create-php-files.html).
- [ ] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Comment by mariuszkrzaczkowski** [comment]
What is needed Id?

**Comment by migoi** [comment]
e.g. if you create a new record, you can directly set the "assigned_user_id". No need to query Users RecordList (which does not exists yet)

**Comment by mariuszkrzaczkowski** [comment]
assigned_user_id field is optional, look here
image

**Comment by mariuszkrzaczkowski** [comment]
if you need to know with what values you can create a record, it is the function to see:
image

image

**Pull request closed without merging**
