### PR TITLE
Improve Translation

### PR DESCRIPTION
**Pull request by waw555**
## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code is written according to the guidelines found [here] (https://yetiforce.com/en/developer-documentation/standards/167-how-to-create-php-files.html).
- [ ] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Comment by paula-w** [comment]
Do you want us to merge this one? Or will you submit a new one?

**Comment by waw555** [comment]
Today it all. With the main transfer I finished proofreading and more minor fixes the meaning.

**Comment by paula-w** [comment]
So we wait for the fixed version?

**Comment by waw555** [comment]
No. Corrections will I do in version 3.2

**Pull request closed without merging**
