### PR TITLE
Adding Spanish translation, mostly WIP!

### PR DESCRIPTION
**Pull request by fernandogiacomino**
## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [ ] My code is written according to the guidelines found [here](https://yetiforce.com/en/developer-documentation/standards/167-how-to-create-php-files.html).
- [x] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

**Comment by paula-w** [comment]
@fernandogiacomino can you send us an email to cla@yetiforce.com so we could contact you in regards to the translation?

**Comment by jstorchia** [comment]
Gracias fernando si necesitas ayuda avísame .

**Comment by fernandogiacomino** [comment]
Juanchi, por ahora voy traduciendo de a poco. Soy nuevo en github y no conozco bien la forma correcta de colaborar, se aceptan sugerencias. Saludos

**Comment by paula-w** [comment]
We cannot merge this pull request without a signed CLA. Please refer to the emails we sent you.

**Comment by mariuszkrzaczkowski** [comment]
Closed due to missing signed CLA, and lack of contact with the author.

**Pull request closed without merging**
