### PR TITLE
Added database integrity checker as cli tool

### PR DESCRIPTION
**Pull request by dataviper**
In vtiger and yetiforce I stumbled upon a broken page on some occassions. The reason was always a missing column/table/row or missing entry in a config column.

Now you can check for installation error concerning the db

### CODE REVIEW

**Comment by paula-w** [comment]
Hi,
Thanks for the request. We appreciate it.
First of all, we will need you to sign CLA with us (I'll mail it to you)

Some comments to your pull request:
1. The file is missing the license info.
2. This script should not be in the system by default. We made a new YF repository for it (https://github.com/YetiForceCompany/YetiForceScripts). We'll add all extra scripts and tools here. 
Create a new directory with your script in YetiForceScripts and send us a pull request.
3. Add some manual on how to use your script and what is required in order for it to work properly.

**Comment by acidhunter** [comment]
any news about this?

**Comment by paula-w** [comment]
We're waiting for @dataviper to add the missing info and move the request to https://github.com/YetiForceCompany/YetiForceScripts

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceScripts/commit/03382c14c76622f2c7756fc91990d96825ce0189

**Pull request closed without merging**
